- docs/layouts.md
- lib/jekyll-archives/archive.rb
- test/test_jekyll_archives.rb
Moves the Date object from `page.title` to `page.date`:
- In case of a non-date archive, `page.title` is the name of the category or tag, and `page.date` is `nil`
- In case of a date archive, `page.title` is `nil` and `page.date` is the Date object previously stored in `page.title`
---
---
Addresses #20.
> Move Date object from `page.title` to `page.date`

- docs/layouts.md
If I understand the changes correctly, we should use `page.date` on date-based archives pages, as `page.title` will return `nil`.
> Update documentation to reflect changes in v2.0.0

- .gitignore
- .travis.yml
- Gemfile
- jekyll-archives.gemspec
- lib/jekyll-archives.rb
- script/cibuild
Incremental regen messes up the content of generated archives (they show raw content instead of generated content), so we need to disable it if `jekyll-archives` is included as a gem.
_Should_ fix the failing test(s) from #47.
@parkr @pathawks
> Disable incremental regen when Archives enabled for 3.0 compatibility

- .travis.yml
- lib/jekyll-archives/version.rb
@alfredxing 
@parkr 
I'm using [Bundler](http://bundler.io) in order to manage gem dependencies for Jekyll. In order to upgrade to Jekyll 3, I was running the command `bundle update`. Unfortunately Bundle wasn't upgrading to v3.0.0 and was still using Jekyll 2. After investigation i found out only removing "jekyll-archives" from the Gemfile will solve the problem. 
Reason: 
The [Gem page on RubyGems.org](https://rubygems.org/gems/jekyll-archives) is using v2.0.0 with the fixed dependency `jekyll ~> 2.4`. See attached screenshot.
On the master branch (aka HEAD) the dependency issue is already [fixed](https://github.com/jekyll/jekyll-archives/blob/master/jekyll-archives.gemspec#L16).
So let's increase the version of Jekyll-Archives, so that the changes for Jekyll 3 will be available on …
> Update Jekyll-Archives on RubyGems.org to support Jekyll 3

- lib/jekyll-archives.rb
@parkr It works! I think originally I wasn't too sure because this now uses the site's posts object instead of ours, but they should be the same anyways.
@paulrobertlloyd I've kept your commits in here since we do still need the checks when constructing the archives by year. Thanks for your work on this!
> Support revised documents/collections in Jekyll 3 (v2)

- lib/jekyll-archives.rb
- lib/jekyll-archives/archive.rb
I have a site which uses years as tags. Because this value previously checked for String objects only, the slug would not be set, and the value would be nil for later where a crash would occur.
Forcing a to_s and checking length will allow numbers, or pretty much any object that is listed under tags to get through.
> Slug Creation Should Allow Numbers

- .travis.yml
- Gemfile
Activesupport kept complaining about Ruby versions, so use an older version (taken from Jekyll Gemfile) if Ruby version is < 2.2.2
Also, update Travis config with newer Jekyll & newer Ruby's
> Update Travis config and Gemfile for Ruby < 2.2.2 support

- lib/jekyll-archives.rb
- lib/jekyll-archives/archive.rb
Make Archive a subclass of Jekyll::Page, and render it using the regular Page pipeline. This should also fix long-standing issue #28.
As with incremental regen, this would still be affected by the post-listing content bug (which I'm still thinking about how to fix!). So if users are going to use `{{ post.content}}` on archive pages, they'll probably still have to disable incremental for now.
> Make Archive subclass of Page

- lib/jekyll-archives.rb
- lib/jekyll-archives/archive.rb
I put this together quickly, seems to work for me. May need to track other dependencies.
> Enable incremental operation

- .travis.yml
Hello @jekyll/archives. In the interests of keeping development of this important (IMHO!) plugin progressing, and in the spirit of being proactive (and following on from the discussion in #58), I’ve updated the Travis tests to remove tests for Ruby 1.9 ~~/Jekyll 2.0~~.
~~Somewhat related, I removed the version forking in the code, and bumped the minimum supported Jekyll version to 3.0. Controversial? Maybe, but Jekyll 3.0 is 15 months old now. *Ducks*~~
> Remove Travis test for Ruby 1.9

- .rubocop.yml
- .travis.yml
- Gemfile
- Rakefile
- jekyll-archives.gemspec
- lib/jekyll-archives.rb
- lib/jekyll-archives/archive.rb
- lib/jekyll-archives/version.rb
- test/helper.rb
- test/test_jekyll_archives.rb
This PR is the result of adding `inherit_gem: jekyll: .rubocop.yml` to `.rubocop.yml` and running `rubocop -a` so that this project follows Jekyll core's coding styles for consistency like other core plugins. This way, as Jekyll's Ruby style changes, so too will this project's.
> Inherit Jekyll's rubocop config for consistency

- lib/jekyll-archives.rb
- lib/jekyll-archives/archive.rb
Reviewing the commit history of this plugin, it seems that somewhere between #67 and #58 being merged in, deprecated code that was removed was added back in again later.
The first merge, in which `Archive` became a subclass of `Page`, removed defs that were no longer required as part of this change. The merge that appears to reintroduce them is the one adding support for incremental rebuilds.
Have I read this correctly? Can we delete some code?!
> Remove deprecated defs

- docs/configuration.md
A complete Jekyll / Ruby noob here.
If you like, I'll create another pull request, adding the steps to get this up and running to the main README?
> docs/configuration: GitHub table display was messed up

- README.md
In `_config.yml`, the 'gems' configuration option has been renamed to 'plugins'.
> Update Readme Installation Guide

- docs/configuration.md
This is a 🔦 documentation change.
Removed single quotes around layout value in default configuration to match the style of the rest of the page.
Add category layout in sample values.
> Small updates for consistency across document

- .travis.yml
- Gemfile
- jekyll-archives.gemspec
Minimal changes to allow testing with Jekyll 4.0 pre-release.
(*Should we drop support for Ruby 2.2 here for consistency?*)
> Allow testing and using with Jekyll 4.x

- lib/jekyll-archives.rb
Since we're calling `config.fetch` invariably without handling `nil`, its better that we set the optional parameter as an empty hash lest a `NoMethodError: undefined method 'fetch' for nil:NilClass` be raised.
The reason why this remained concealed all this while is because `Jekyll::Site` automatically initializes all `Jekyll::Generator` subclasses with `site.config`. Therefore, this change is not going to cause any impact whatsoever, but is correcting a wrong nevertheless.
> Initialize Archives generator with a hash

- lib/jekyll-archives.rb
The `gemspec` dropped support for versions older than `Jekyll 3.1` in https://github.com/jekyll/jekyll-archives/commit/a7a5a84cd398e9e3484a7719ce18ee9931ad8392 which is part of latest released version.
This removes the now redundant code to support legacy Jekyll versions
> Remove support for legacy Jekyll versions

- lib/jekyll-archives.rb
`Jekyll::Site#tags` and `Jekyll::Site#categories` (introduced in Jekyll 2.0 via https://github.com/jekyll/jekyll/commit/8c0e5d8d98b2713339d4c73359017e8303c684af) already encapsulate the exact same logic:
```ruby
def post_attr_hash(post_attr)
hash = Hash.new { |h, key| h[key] = [] }
posts.docs.each do |p|
p.data[post_attr].each { |t| hash[t] << p } if p.data[post_attr]
end
hash.each_value { |posts| posts.sort!.reverse! }
hash
end
def tags
post_attr_hash("tags")
end
def categories
post_attr_hash("categories")
end
```
So, we might as well just delegate to the methods in `Jekyll::Site`.
However, it's not much of a concern since `Archives#tags` and `Archives#categories` are called at most just once per call to the `Archives#generate` method.
--
*Notes:
- I refrained from using `extend …
> Read-in site's tags and categories attributes

- lib/jekyll-archives.rb
- test/helper.rb
- test/test_jekyll_archives.rb
If the user or a third-party plugins *sets* `config["jekyll-archives"]` to `nil` or something but a Hash, output a warning and turn-off the archives generator.
Closes #138
> Return unless 'jekyll-archives' config is a Hash

- lib/jekyll-archives/archive.rb
Minor refactoring to micro-optimize certain methods
> Access nested Hash values with `Hash#dig`

- lib/jekyll-archives/archive.rb
So that it is not computed on every call.
> Memoize relative_path attribute of archive pages

- lib/jekyll-archives/archive.rb
So that a new `Date` object is not created on every call
> Memoize date attribute of date-type archive pages
